enum NodeType {
  INITIAL = "INITIAL",
  MANUAL_TRIGGER = "MANUAL_TRIGGER",
  HTTP_REQUEST = "HTTP_REQUEST",
  GOOGLE_FORM_TRIGGER = "GOOGLE_FORM_TRIGGER",
  STRIPE_TRIGGER = "STRIPE_TRIGGER",
  ANTHROPIC = "ANTHROPIC",
  OPENAI = "OPENAI",
  GEMINI = "GEMINI",
  CRON = "CRON",
  DISCORD = "DISCORD",
  SLACK = "SLACK",
}

export default NodeType;

